/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atminterface;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;

/**
 *
 * @author shivb
 */
public class Withdraw extends javax.swing.JFrame {

    /**
     * Creates new form Withdraw
     */
    String id="";
    public Withdraw(String id) {
        this.id=id;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        wdamount = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Welcome "+id);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 202, 180, 30));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, -1));

        jLabel3.setText("Enter amount to withdraw :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 150, 20));

        wdamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wdamountActionPerformed(evt);
            }
        });
        getContentPane().add(wdamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 150, -1));

        jButton2.setText("Withdraw");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atminterface/Atm.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Dashboard db=new Dashboard(id);
dispose();
db.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void wdamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wdamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wdamountActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
float wdam=Integer.parseInt(this.wdamount.getText());
        float wdamount=(float)wdam;
        LocalDateTime date= LocalDateTime.now();
                
        int dbamount=5000;
        try{
         Class.forName("com.mysql.cj.jdbc.Driver");  
        Connection con=DriverManager.getConnection(  "jdbc:mysql://localhost:3307/task2","root",""); 
           Statement statement;
            statement = con.createStatement();            
            ResultSet rs;
            rs = statement.executeQuery("select Balance from accountbal where Uid= '"+id+"'");
            
           
            
           while (rs.next()) {
                dbamount = rs.getInt("Balance");
                
            }
            System.out.println(dbamount);
           if(dbamount>wdamount){
           dbamount-=wdamount;
           System.out.println(dbamount);
           statement.executeUpdate("update accountbal set Balance='"+dbamount+"' where Uid= '"+id+"'");
           statement.executeUpdate("insert into transactionh (Uid, trtype, amount, balance, datetime)values('shivbhor44','Withdraw','"+wdamount+"','"+dbamount+"','"+date+"')");
           JOptionPane.showMessageDialog(null    ,"Money withdraw successfully ");
           }else if(dbamount<wdamount){
           JOptionPane.showMessageDialog(null    ,"Low account balance");
           }
           statement.close();
            con.close();
           
     }catch(Exception e){
         System.out.println(e);
     
     }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField wdamount;
    // End of variables declaration//GEN-END:variables
}
